// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWa1JAxa99n9gqEVCxTlpYDZro6y0doFY',
    appId: '1:28701956439:web:31a5a4f274f0c741b8c612',
    messagingSenderId: '28701956439',
    projectId: 'expense-tracker-9b6ca',
    authDomain: 'expense-tracker-9b6ca.firebaseapp.com',
    storageBucket: 'expense-tracker-9b6ca.firebasestorage.app',
    measurementId: 'G-JZC88D4Y02',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRjJ6Ab3HC7tL9Ckn9aZ5lRFUbYtZ1So',
    appId: '1:28701956439:android:379e2412ac5beb2eb8c612',
    messagingSenderId: '28701956439',
    projectId: 'expense-tracker-9b6ca',
    storageBucket: 'expense-tracker-9b6ca.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuR_8qPEXOTpzTtAKYv6qgLf1r3CF-4DE',
    appId: '1:28701956439:ios:9dc3ade180b5e5e9b8c612',
    messagingSenderId: '28701956439',
    projectId: 'expense-tracker-9b6ca',
    storageBucket: 'expense-tracker-9b6ca.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerOffline',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuR_8qPEXOTpzTtAKYv6qgLf1r3CF-4DE',
    appId: '1:28701956439:ios:9dc3ade180b5e5e9b8c612',
    messagingSenderId: '28701956439',
    projectId: 'expense-tracker-9b6ca',
    storageBucket: 'expense-tracker-9b6ca.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerOffline',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWa1JAxa99n9gqEVCxTlpYDZro6y0doFY',
    appId: '1:28701956439:web:69e53428c920515cb8c612',
    messagingSenderId: '28701956439',
    projectId: 'expense-tracker-9b6ca',
    authDomain: 'expense-tracker-9b6ca.firebaseapp.com',
    storageBucket: 'expense-tracker-9b6ca.firebasestorage.app',
    measurementId: 'G-VXR1B76FYP',
  );
}
